name: Windows Build Test

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10

    env:
      BUILD_PLATFORM: x64
      BUILD_CONFIGURATION: Release

    steps:
      - uses: actions/checkout@v4
        with:
          repository: wolfssl/wolfssl
          ref: master
          path: wolfssl

      - uses: actions/checkout@v4
        with:
          path: wolfclu

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore wolfSSL NuGet packages
        run: nuget restore wolfssl/wolfssl64.sln

      - name: Replace user_settings.h
        run: cp wolfclu/ide/winvs/user_settings.h wolfssl/IDE/WIN/user_settings.h

      - name: Build wolfSSL
        run: msbuild /m /p:Platform=${{ env.BUILD_PLATFORM }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} wolfssl/wolfssl64.sln

      - name: Restore wolfCLU NuGet packages
        working-directory: wolfclu
        run: nuget restore wolfclu.sln

      - name: Build wolfCLU
        working-directory: wolfclu
        run: msbuild /m /p:Platform=${{ env.BUILD_PLATFORM }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} wolfclu.sln

      - name: Run tests
        working-directory: wolfclu
        run: python tests/run_tests.py

